name: Compile JSX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile_jsx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm ci
      
    - name: Transpile JSX
      run: npx babel src --out-dir dist
      
    - name: Build application
      run: npm run build