name: Compile JSX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile_jsx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 20.x, 21.x]
    steps:   
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm install
      
    - name: Transpile JSX
      run: npx babel src --out-dir dist
      
    - name: Build application
      run: npm run build